### ISSUE TITLE
Todo for stable

### ISSUE THREAD

**Issue by PeeHaa** [ekinhbayar/gitamp#47]
- [ ] Do we really need auryn? Or is it easier to just build the deps ourselves as we do not have a deep stack?
- [ ] We need to allow users to have the server listen on several ips/ports (an exampleis both ipv4 and ipv6 support)
- [ ] Abstract the server away in its own class
- [ ] Maybe abstract the special repositories to a dedicated class instead of repeating it (maybe even make it a config?)
- [ ] Change `new Type(1),` etc to not make use of magic numbers
- [ ] Make exception extend the base project exception instead of the global \Exception
- [ ] Instead of asking for a concrete `HttpClient` class maybe ask for an interface instead?
- [ ] Everything that returns a `\Generator` right now should return a Promise
- [ ] https://github.com/ekinhbayar/gitamp/pull/46/commits/2f48b31f38b8289054e91916ab0b9a390d1a7443#diff-1b3db3c3ba01baa1e657a2965f6771a6R30 should not be nullable, but instead be an empty results
- [ ] Instead ofusing the onclose on the client (https://github.com/ekinhbayar/gitamp/pull/46/commits/2f48b31f38b8289054e91916ab0b9a390d1a7443#diff-1b3db3c3ba01baa1e657a2965f6771a6R52) we can just log the disconnect after this loop https://github.com/ekinhbayar/gitamp/pull/46/commits/2f48b31f38b8289054e91916ab0b9a390d1a7443#diff-1b3db3c3ba01baa1e657a2965f6771a6R77
- [ ] Test with lowest deps
- [ ] Test with highest deps
- [ ] Test with php 8 if travis made a working image yet

**Comment by ekinhbayar** [comment]
Here's [an example](https://github.com/amphp/http-server/blob/master/examples/hello-world.php#L19-L22) for supporting SSL for http-server.
